---
title: "MATH 4753 Laboratory 1"
author: "Landon Alexander"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Tasks

## Task 1
  
```{r}
getwd()
```
## Task 2
```{r}

ddt <- read.csv("DDT-1.csv")
head(ddt)
```
## Task 3

1. The qualitative variables are RIVER and SPECIES
2. The quantitative variables are MILE, LENGTH, WEIGHT, and DDT

```{r}
summary(ddt)
```
3. There are three SPECIES in the ddt data set

```{r}
with(ddt, ddt[WEIGHT>800 & SPECIES=="LMBASS",])

with(ddt, ddt[DDT>4.0 & RIVER=="SCM",])
```
## Task 4
1. 42.8125
```{r}
mean(ddt$LENGTH)
```
2. 376.5461
```{r}
sd(ddt$WEIGHT)
```
3. 0
```{r}
plot(LENGTH ~ WEIGHT, data = ddt)

plot(WEIGHT ~ LENGTH, data = ddt)
```

4. 1.00
```{r}
v=1:20
v/20
```

## Task 5
```{r}
spriv=with(ddt,table(RIVER))
spriv
barplot(spriv, col = rainbow(4))
```
```{r}
spriv=with(ddt,table(RIVER,SPECIES))
spriv
barplot(spriv,beside=TRUE,col= rainbow(4))

```

## Task 6
```{r}
sp=with(ddt,table(SPECIES))
pie(sp, col = rainbow(4))
```
```{r}
sp=with(ddt,table(RIVER))
pie(sp, col = rainbow(4))

```

## Task 7
```{r}
with(ddt,boxplot(DDT,ylab="DDT",col="blue",notch=TRUE))
```
```{r}
with(ddt,boxplot(WEIGHT,ylab="WEIGHT",col="green",notch=TRUE))
```
```{r}
with(ddt,boxplot(LENGTH,ylab="LENGTH",col="red",notch=TRUE))
```

## Task 8
```{r}
rivcol=with(ddt, ifelse(RIVER=="FCM","Red",
                        ifelse(RIVER=="LCM","Blue",
                               ifelse(RIVER=="SCM","Green","Black"))))
coplot(LENGTH~WEIGHT|RIVER,data=ddt, col = rivcol)
```
```{r}
fishcol=with(ddt,ifelse(SPECIES=="CCATFISH","Red",
                        ifelse(SPECIES=="SMBUFFALO","Blue","Green")))
coplot(DDT~WEIGHT|SPECIES,data=ddt, col = fishcol)
```

## Task 9
```{r}
library(ggplot2)

gb = ggplot(ddt, aes(x = SPECIES, y= WEIGHT, fill = RIVER)) + geom_boxplot() + ggtitle("Landon Alexander")
print(gb)
```
```{r}
library(ggplot2)
gb = ggplot(ddt, aes(x = RIVER, y= LENGTH, fill = SPECIES)) + geom_violin() + ggtitle("Landon Alexander")
print(gb)
```
```{r}
library(ggplot2)
gb = ggplot(ddt, aes(x = WEIGHT, y= LENGTH, color = SPECIES)) + geom_point() + ggtitle("Landon Alexander")
print(gb)
```
